### PR TITLE
Closes #1975: Remove unused locales' strings.xml! 🔄

### LINKED ISSUE #1975: Remove locales that aren't supported
Seems like a bunch of non-supported (and so, non-shipping) localized files are still present in the Firefox Echo Show code base. Since there is no in-app locale switcher, there's not much sense in keeping them.
The list of Amazon shipping locales we were given at the time were:
zh-CN (Simplified Chinese)
fr (French)
de (German)
it (Italian)
ja (Japanese)
pt-BR (Brazilian Portuguese)
es-ES (Spanish from Spain)

@athomasmoz  Can you please confirm this is still the current list we need?
(also CC @Pike and @mcomella for info)
thanks!

### PR DESCRIPTION
**Pull request by mcomella**
The list of desired locales, as mentioned in the issue, is:
zh-CN (Simplified Chinese)
fr (French)
de (German)
it (Italian)
ja (Japanese)
pt-BR (Brazilian Portuguese)
es-ES (Spanish from Spain)

After this change, we see the remaining locales:
find . -name "strings.xml" | sort
./values-de/strings.xml
./values-es-rES/strings.xml
./values-fr/strings.xml
./values-it/strings.xml
./values-ja/strings.xml
./values-pt-rBR/strings.xml
./values-zh-rCN/strings.xml
./values/strings.xml

### Pull Request checklist

- [x] This PR includes thorough **tests** or an explanation of why it does not
  - Just removing locales. I guess we can write static analysis to verify we only have the needed locales... but it's probably not worth it
- [x] This PR includes a **CHANGELOG entry** or does not need one
- [x] I have considered adding **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-denied`)

### CODE REVIEW

**Comment by mcomella** [comment]
TC failed with no space left on device: re-running.

**Comment by liuche** [comment]
```
* What went wrong:
Execution failed for task ':app:validateReleaseConfiguration'.
> Unable to build release builds with uncommitted changes
```

**Comment by mcomella** [comment]
It looks like our generated LocaleList.java code is actually checked into version control so I'll have to check the changes in.

**Comment by mcomella** [comment]
@liuche Please land this for me (assuming there are no issues).

**Pull request merged**
