### PR TITLE
No issue: update Security Issue link so 'Restrict access' checkbox is…

### PR DESCRIPTION
**Pull request by mcomella**
… checked.

Reviewer: please ensure the link is correct & the "Restrict access" checkbox is checked.

## Checklist

- [ ] Confirm the **acceptance criteria** is fully satisfied in the issue(s) this PR will close
- [ ] Add thorough **tests** or an explanation of why it does not
- [ ] Add a **CHANGELOG entry** if applicable
- [ ] Add **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-notneeded`)

### CODE REVIEW

**Comment by mcomella** [comment]
@Baron-Severin
* Can you see "Firefox for FireTV" on this page? https://bugzilla.mozilla.org/enter_bug.cgi For some reason, it appears with a lock for me so perhaps it is locked down
* Where does the existing link in our current readme take you? Same error?

**Comment by Baron-Severin** [comment]
>     * Can you see "Firefox for FireTV" on this page? https://bugzilla.mozilla.org/enter_bug.cgi For some reason, it appears with a lock for me so perhaps it is locked down
Nope, don't see it there.

>     * Where does the existing link in our current readme take you? Same error?
Existing link takes me to `Sorry, either the product Firefox for FireTV does not exist or you aren't authorized to enter a bug into it. `

**Comment by mcomella** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1571064 to make FFTV non-private on Bugzilla.

**Comment by mcomella** [comment]
@dnarcese Can you check that the link is working correctly & the "Restrict access" checkbox is checked? In the upstream bug, they said the configuration should be updated.

**Comment by dnarcese** [comment]
@mcomella I am still getting the error message "Sorry, either the product Firefox for FireTV does not exist or you aren't authorized to enter a bug into it." I can see the component in Bugzilla but I can't file a bug.

**Comment by mcomella** [comment]
@dnarcese Can you click the link that's already in our README and verify that 1) you get the "file a bug" tempalte and 2) that "Restrict access to... security" is already checked? It seems it may have been fixed on the Bugzilla side

**Comment by dnarcese** [comment]
@mcomella I get the correct template, but no checkboxes are checked.

**Comment by mcomella** [comment]
> @mcomella I get the correct template, but no checkboxes are checked.

Not the one down the bottom here? And to be explicit, I mean the README on master:

image

Sorry to double-check but Emma confirmed it from her non-work account and I see the same behavior so I just want to check with you too. Perhaps you need to enable advanced options?

You could also try filing a test bug and confirm it gets filed as a security issue.

**Comment by dnarcese** [comment]
@mcomella 
Yup, this is what I get. image

**Comment by mcomella** [comment]
@dnarcese Can you file a bug without checking the box and see if it gets filed as a security bug? We have it set up so security is "mandatory". Sorry, I didn't think to ask this explicitly before. I know this is tedious. x_x

**Comment by dnarcese** [comment]
@mcomella Is this the expected result
image

**Comment by mcomella** [comment]
Yep, lgtm, thanks.

**Pull request closed without merging**
