### PR TITLE
NO MERGE - Issue #2378: Add --info to TC gradle job!!:(:(:(

### PR DESCRIPTION
**Pull request by mcomella**
This prints test names and will help us debug.

### Pull Request checklist

- [ ] This PR includes thorough **tests** or an explanation of why it does not
- [ ] This PR includes a **CHANGELOG entry** or does not need one
- [ ] I have considered adding **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-denied`)

### CODE REVIEW

**Comment by mcomella** [comment]
TC got through to  firebase step: restarting.

**Comment by mcomella** [comment]
TC passed again (WTF?). Restarting.

**Comment by mcomella** [comment]
TC never fails: is this still a problem in other PRs?

**Comment by mcomella** [comment]
I wonder if we can reproduce this is our Docker instance locally.

**Comment by dnarcese** [comment]
Just failed for me in https://taskcluster-ui.herokuapp.com/tasks/W3yRXJv7T6SPS7bQzwiyzw/runs/0/logs/https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FW3yRXJv7T6SPS7bQzwiyzw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

**Comment by dnarcese** [comment]
It's failing now! 😃

**Comment by mcomella** [comment]
The failure happened on:

```
org.mozilla.tv.firefox.pocket.PocketVideoRepoTest > GIVEN pocket key is not valid WHEN getting a new instance THEN feed state starts no api key STANDARD_OUT
    [Robolectric] org.mozilla.tv.firefox.pocket.PocketVideoRepoTest.GIVEN pocket key is not valid WHEN getting a new instance THEN feed state starts no api key: sdk=28; resources=binary

[taskcluster:error] Task timeout after 3600 seconds. Force killing container.
[taskcluster 2019-06-12 20:17:05.911Z] === Task Finished ===
```

We could investigate this test or see if there is another task that is taking a long time, making this task run so late this fails.

**Comment by mcomella** [comment]
Closing in favor of #2459.

**Pull request closed without merging**
