### PR TITLE
Issue #818: Update colors and icons

### PR DESCRIPTION
**Pull request by pocmo**
(This is a rebased and squashed version of PR #1024).

* Issue #818: Fix search bar colours
* Issue #818: Fix pocket tile colours
* Issue #818: Fix background colour
* Issue #818: Fix nav buttons colours
* Issue #818: Use photon colours directly
* Issue #818: Use android-components icons
* Issue #818: Fix search icon colour
* Issue #818: Flip pin icon

### CODE REVIEW

**Comment by pocmo** [comment]
I'm curious if this PR passes on travis..

**Comment by pocmo** [comment]
@dnarcese @Baron-Severin This seems to pass now... (Not sure what's wrong with Travis on the other branch).

**Comment by liuche** [comment]
@dnarcese can you include a new screenshot for @aminalhazwani so it's easier for him to visually review?

**Comment by aminalhazwani** [comment]
The colors are also inspectable here https://firefoxux.github.io/people/aalhazwani/firefox-for-fire-tv/homescreen-pocket-tile/v11/index.html#artboard0

**Comment by dnarcese** [comment]
@aminalhazwani 

> the icons fills seem off, especially if you look at the difference between the reload icon and the pin one. I listed all colors here #818 (comment), if you point me to the file where those colors are applied I can go through them

The pin icon is coming from android-components and there is an alpha set there, which is why the fill colour is off- I will look into getting that changed. 
> can you point me to the Firefox logo asset so that I update the color of the work "Firefox"? Thanks!

Firefox logo is at res/drawable/ic_firefox_and_workmark.png

> I also have another question, is the color of the Help button in the Pocket view a regression issue of this PR?

Yes, I filed issue #1064 for that!

**Comment by liuche** [comment]
If the pin alpha is the only thing remaining and bugs have been filed for everything, then you should merge this in (with the correct pin orientation) so it doesn't bitrot further, and everything else will propagate through the other bugs.

**Comment by dnarcese** [comment]
I've created issue #1094 for the pin icon and issue #1095 (assigned to @aminalhazwani) for the Firefox logo colour update

**Pull request merged**
