### PR TITLE
Closes #2447: Handle empty pinnedTile lost focus

### LINKED ISSUE #2447: FF remains stuck after deleting the last pinned tile(after restart works)
## Steps to reproduce
1. Launch FF for Fire TV.
2. Select the `Pinned Tiles`.
3. Select the last tile(or any tile).
4. Delete them until `YouTube` tile remains.
5. Open `YouTube` tile.
6. Tap on the menu button(the FF menu overview is displayed).
7. Select the last tile `YouTube` and delete it.

### Expected behavior
The menu overview is displayed and any section can be reached.
### Actual behavior
The menu overview remains stuck after deleting the last tile.
### Device information
* Fire TV device: **`Fire Stick 2nd Gen.`**
* Latest affected Firefox version: **`FF for Fire TV 3.1.1-LAT2`**
* Earliest affected Firefox version: **`FF for Fire TV 3.1.1-LAT2`**
* Turbo Mode: **`On and Off`**
### Notes
[logcat.txt](https://github.com/mozilla-mobile/firefox-tv/files/3310990/logcat.txt)
**Please note that this issue occurs only once, after restarting FF for fire tv everything works as expected.**

### PR DESCRIPTION
**Pull request by psymoon**
### Pull Request checklist

- [x] This PR includes thorough **tests** or an explanation of why it does not
- [x] This PR includes a **CHANGELOG entry** or does not need one
- [x] I have considered adding **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-denied`)

### CODE REVIEW

**Comment by mcomella** [comment]
As per my comments in the issue https://github.com/mozilla-mobile/firefox-tv/issues/2447#issuecomment-505185422, this issue may be a dupe of another issue we have a lower priority on: #2398. As such, I'll hold off on the full review until we get more information.

**Comment by mcomella** [comment]
> I commented out the <requestFocus> tag and could no longer reproduce this bug.

Michelle pointed out this is untrue and I confirmed that.

**Comment by mcomella** [comment]
@wmichelle024 Given all the focus work you've been doing recently, does this solution fall in line with your updated focus code and is something I should re-review? If so, please request me to re-review. :)

**Comment by wmichelle024** [comment]
@mcomella The solution looks fine in terms the new focus handling, but would this only solve the problem with the pinned tiles channel? I think the same issue occurs with deleting any of channels, but the solution looks specific to the pinned tiles (please correct me if I'm wrong).

**Comment by mcomella** [comment]
We spoke IRL: this is a good point. We should implement a solution that works across multiple channels. I'm going to close this PR (and link it from the bug) because we'll want to come up with this more generic solution.

**Pull request closed without merging**
