### PR TITLE
Issue #2378 !!!!!!!!!

### PR DESCRIPTION
**Pull request by dnarcese**
Using this PR to debug the TC failures.

Things I've tried:

- [x] reverts commit f8a1c44bf8c52d3ed92b718b880a9b5eb5fcd24b.
  - failed on `testGeckoDebugUnitTest`
- [x] reverts commit 7f81b44
  - passed 5/5
- [x] ignore `PocketVideoRepoTest`s with `blockingFirst`  ([here](https://searchfox.org/mozilla-mobile/source/firefox-tv/app/src/test/java/org/mozilla/tv/firefox/pocket/PocketVideoRepoTest.kt#92) and [here](https://searchfox.org/mozilla-mobile/source/firefox-tv/app/src/test/java/org/mozilla/tv/firefox/pocket/PocketVideoRepoTest.kt#98))
- [x] change `org.gradle.parallel` property in `gradle.properties` to `false`
  - passed (it is actually false by default so this change doesn't matter)
- [x] change `org.gradle.jvmargs` property in `gradle.properties` to `4096`
  - failed
- [x] test locally in our docker image
  - build failed with 
`Unable to clear jar cache after compilation, maybe daemon is already down: java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is:
	java.net.ConnectException: Connection refused (Connection refused)
Could not connect to kotlin daemon. Using fallback strategy.`
^ this was probably due to low Java heap
After changing these settings to increase memory, the build is passing:
```
org.gradle.daemon=false
kotlin.incremental=false
org.gradle.jvmargs=-Xmx4096m
org.gradle.parallel=false
```

### Pull Request checklist

- [ ] This PR includes thorough **tests** or an explanation of why it does not
- [ ] This PR includes a **CHANGELOG entry** or does not need one
- [ ] I have considered adding **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-denied`)

### CODE REVIEW

**Comment by dnarcese** [comment]
After trying each property one by one, it seems that this combination passes
```
org.gradle.daemon=false
kotlin.incremental=false
org.gradle.jvmargs=-Xmx4096m
```

**Comment by dnarcese** [comment]
The combinations I tried:

```
org.gradle.jvmargs=-Xmx4096m 
//FAILED
```


```
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx4096m 
//FAILED
```


```
org.gradle.jvmargs=-Xmx4096m
kotlin.incremental=false 
//PASSED
```


```
org.gradle.daemon=false
kotlin.incremental=false
org.gradle.jvmargs=-Xmx4096m 
//PASSED
```

**Comment by mcomella** [comment]
@dnarcese My Docker build also failed with `Unable to clear jar cache after compilation, maybe daemon is already down:` but after increasing the gradle daemon heap, I got the same error. I increased the memory **available to docker in the docker settings** on my machine and it appears to have fixed the issue. I still can't reproduce the timeout locally, however.

I'm guessing your solution worked because you disabled the gradle daemon, reducing the amount of memory your builds would use.

**Comment by mcomella** [comment]
I checked with the TC team: they don't think anything they changed could affect this.

One idea they brought up: @dnarcese have we disable *all* the unit test tasks before? If it doesn't fail after doing that, there's a possibility that there is something actually broken in our unit tests (could we bisect?).

**Comment by dnarcese** [comment]
@mcomella No I never tried disabling them all - we can try that next.

**Comment by dnarcese** [comment]
Removing test task successes: 0/0

**Comment by dnarcese** [comment]
Ignoring `PocketVideoRepoTest` with `blockingFirst`: 0/0

**Comment by dnarcese** [comment]
Maybe it's a robolectric bug? 
I updated to the latest version: passes 0/0

**Pull request closed without merging**
