### PR TITLE
[DO NOT MERGE] mcomella PR to test TC fixes!

### PR DESCRIPTION
**Pull request by mcomella**
### Pull Request checklist

- [ ] This PR includes thorough **tests** or an explanation of why it does not
- [ ] This PR includes a **CHANGELOG entry** or does not need one
- [ ] I have considered adding **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-denied`)

### CODE REVIEW

**Comment by mcomella** [comment]
Things to try (each of these will be done independent from one another):
- [x] Revert commits in v3.10 to upgrade gradle & app/build dependencies (except for a-c)
- [ ] Talk with TC team to see if they changed anything that could affect this
- [ ] 

N.B.: Daniela has explored many solutions already in #2431.

**Comment by mcomella** [comment]
This has already passed 3 times today (first three exclamation points).

**Comment by dnarcese** [comment]
Fourth retry timed out on `testGeckoDebugUnitTest`

**Comment by mcomella** [comment]
Hey, stop working!

**Comment by mcomella** [comment]
I pushed git tag `v3.4`: let's see if a really old revision will trigger the failures.

**Comment by mcomella** [comment]
It's also possible the a-c upgrade I made with the other dependency upgrades caused the intermittent.

**Comment by dnarcese** [comment]
Wow 8 minutes! It used to be so fast

**Comment by mcomella** [comment]
> Wow 8 minutes! It used to be so fast

Yeah, wow. I'm going to comment in the unexpectedly slow builds bug: #2463 This will be easy to retrigger!

Also, stop working. 😾

**Comment by mcomella** [comment]
6 passes and no failures on `v3.3`. Let's try `v3.9`.

**Comment by mcomella** [comment]
One success on `v3.9`.

**Comment by mcomella** [comment]
Pushing v3.10.

**Comment by mcomella** [comment]
Just pushed `v3.11`: let's see how it goes. Success count: 0, no failures.

**Comment by mcomella** [comment]
`v3.11` failed but `v3.10` did not: perhaps the change that broke TC is between those commits.

**Comment by mcomella** [comment]
Interesting: v3.10-LAT4 (which doesn't fork from master, unlike v3.10 which diverges by two commits) is just after the first commit to master that failed: `4641e177`. Let's push `v3.10-LAT4` to see if we can get it to reproduce.

**Comment by mcomella** [comment]
GitHub force closed my PR so I'm now working in #2501.

**Pull request closed without merging**
