### PR TITLE
Fixes #2060: R8 and byte-level optimizations should be enabled !!

### LINKED ISSUE #2060: R8 and byte-level optimizations should be enabled for release builds
### Vision statement / What / Requirements
All Mozilla Android products should use R8 and byte-level ProGuard optimizations.

### Impact
Switching to R8 will significantly improve release build times. https://android-developers.googleblog.com/2018/11/r8-new-code-shrinker-from-google-is.html

Enabling byte-level optimizations will improve application run times.

### Acceptance criteria
Both R8 and byte-level optimizations are enabled in release builds.

### PR DESCRIPTION
**Pull request by colintheshots**

### CODE REVIEW

**Comment by liuche** [comment]
For context this is the Proguard -> R8 switch, which in theory should simply just improve performance. AC will upgrade when R8 is stable, but it sounded like from @colintheshots that upgrading was easy on Fenix. This one needs a fixup and some regression testing, but if it's easy we might as well.

**Comment by colintheshots** [comment]
There's two parts. 1. Byte-level optimizations in ProGuard can be done without R8, but the Android team at Google is adding significant improvements to R8 for them. The ServiceLoader main thread blockage is a new one coming soon for R8. Enums can be converted to integers even under ProGuard classic. 2. R8 itself is largely about build speed and APK size, but has performance implications alongside the ProGuard optimizations.

**Comment by liuche** [comment]
Not sure if ProGuard isn't properly configured for our project, or if this is something with our CI, but I'll timebox looking at these errors.

```
D8: Unrecognized Kotlin lambda [org.mozilla.tv.firefox.hint.HintBinder$bindHintsToView$displayedDisposable$1]: unexpected annotation: dalvik.annotation.SourceDebugExtension
D8: Unrecognized Kotlin lambda [org.mozilla.tv.firefox.hint.HintBinder$bindHintsToView$displayedDisposable$2]: unexpected annotation: dalvik.annotation.SourceDebugExtension
D8: Unrecognized Kotlin lambda [org.mozilla.tv.firefox.hint.HintBinder$bindHintsToView$displayedDisposable$3]: unexpected annotation: dalvik.annotation.SourceDebugExtension
D8: Unrecognized Kotlin lambda [org.mozilla.tv.firefox.hint.HintBinder$bindHintsToView$displayedDisposable$5]: unexpected annotation: dalvik.annotation.SourceDebugExtension
D8: Unrecognized Kotlin lambda [org.mozilla.tv.firefox.navigationoverlay.NavigationOverlayFragment$initPinnedTiles$$inlined$with$lambda$1]: unexpected annotation: dalvik.annotation.SourceDebugExtension
D8: Unrecognized Kotlin lambda [org.mozilla.tv.firefox.navigationoverlay.ToolbarUiController$setupUrlInput$$inlined$with$lambda$1]: unexpected annotation: dalvik.annotation.SourceDebugExtension
D8: Unrecognized Kotlin lambda [org.mozilla.tv.firefox.pocket.PocketViewModel$Companion$noKeyPlaceholders$2]: unexpected annotation: dalvik.annotation.SourceDebugExtension
D8: Unrecognized Kotlin lambda [org.mozilla.tv.firefox.session.SessionRepo$update$$inlined$let$lambda$1]: unexpected annotation: dalvik.annotation.SourceDebugExtension
D8: Unrecognized Kotlin lambda [org.mozilla.tv.firefox.session.SessionRepo$update$$inlined$let$lambda$2]: unexpected annotation: dalvik.annotation.SourceDebugExtension
D8: Unrecognized Kotlin lambda [org.mozilla.tv.firefox.settings.SettingsFragment$setupSettingsViewModel$6$1]: unexpected annotation: dalvik.annotation.SourceDebugExtension
D8: Unrecognized Kotlin lambda [org.mozilla.tv.firefox.utils.PeriodicRequester$backoffTimes$1]: unexpected annotation: dalvik.annotation.SourceDebugExtension
D8: Unrecognized Kotlin lambda [org.mozilla.tv.firefox.utils.ServiceLocator$sessionRepo$2]: unexpected annotation: dalvik.annotation.SourceDebugExtension
D8: Unrecognized Kotlin lambda [org.mozilla.tv.firefox.webrender.EngineViewCache$getEngineView$2]: unexpected annotation: dalvik.annotation.SourceDebugExtension
D8: Unrecognized Kotlin lambda [org.mozilla.tv.firefox.webrender.cursor.CursorEventRepo$webRenderDirectionEvents$2$7$1]: unexpected annotation: dalvik.annotation.SourceDebugExtension
/root/.gradle/caches/transforms-2/files-2.1/d1d970449b51ae2ebad219dbd1ad883f/jetified-okhttp-3.13.1.jar: D8: Type `org.conscrypt.Conscrypt` was not found, it is required for default or static interface methods desugaring of `void okhttp3.internal.platform.ConscryptPlatform.configureSslSocketFactory(javax.net.ssl.SSLSocketFactory)`
/root/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.24/3f6b4bd4f8dbe8d4bea06d107a3826469b85c3e9/slf4j-api-1.7.24.jar: D8: Type `org.slf4j.impl.StaticMDCBinder` was not found, it is required for default or static interface methods desugaring of `org.slf4j.helpers.NOPMDCAdapter org.slf4j.MDC.bwCompatibleGetMDCAdapterFromBinder()`
/root/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.24/3f6b4bd4f8dbe8d4bea06d107a3826469b85c3e9/slf4j-api-1.7.24.jar: D8: Type `org.slf4j.impl.StaticLoggerBinder` was not found, it is required for default or static interface methods desugaring of `void org.slf4j.LoggerFactory.reportActualBinding(java.util.Set)`
```

**Comment by mcomella** [comment]
This isn't a high priority for us at the moment. R8 is expected to be enabled by default eventually so, to minimize our required effort, we should probably just wait until then.

**Comment by mcomella** [comment]
Thanks for thinking of us, Colin! :)

**Pull request closed without merging**
