### PR TITLE
Closes #425: Upgrade gradle plugin to 3.0.1.

### LINKED ISSUE #425: Upgrade gradle plugin to 3.0.1

### PR DESCRIPTION
**Pull request by mcomella**
This requires three parts:
- Upgrade the plugin
- Remove explicit build tools dep: a version is now supplied with the
android gradle plugin
- Upgrade gradle wrapper version since there's a minimum required
version for the new gradle plugin

Note that I also had to invalidate caches, restart, and clean build
locally or else I saw a build-time error like: "More than one file was
found with OS independent path 'META-INF/app_debug.kotlin_module'". I
discovered this solution here: https://stackoverflow.com/a/45846639/2219998

### CODE REVIEW

**Comment by liuche** [comment]
Build errors:

```
  > Could not find com.android.tools.build:gradle:3.0.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.jar
         https://plugins.gradle.org/m2/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom
         https://plugins.gradle.org/m2/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.jar
```

**Comment by mcomella** [comment]
Apparently Android studio does some special casing and so this only builds when building via gradle and the CL. *sign* looking into it...

**Comment by mcomella** [comment]
Current state: works except for:
- A background thread NPE (I think the RuntimeEnvironment aren't initialized yet since it's happening concurrently and it doesn't crash when using the debugger)
- SessionManagerTest hangs for testAmazonWebViewBeta/Release, but no other build variants (wtf?)

I do wonder if these errors are related.

NPE:
```
Exception in thread "SearchEngines-Load" java.lang.NullPointerException
        at org.robolectric.shadows.ShadowAssetManager.getAssetsDirectory(ShadowAssetManager.java:986)
```

**Comment by mcomella** [comment]
I've got most everything working except that `SessionManagerTest` hangs in the amazonWebViewBeta/Release configurations (but not the Debug one; not that Beta/Release aren't proguarded so I think they're pretty similar to Debug) and I'm stumped. It seems to stop intermittently in certain tests but I can't seem to identify a reliable pattern.

The test stops after `@After` but before `@Before` of the next test (discovered with log statements). Here's the thread dump of the main thread:
```"main" #1 prio=5 os_prio=31 tid=0x00007ff27980a000 nid=0x2703 waiting on condition [0x00007000087f2000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076feadb18> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at android.app.SharedPreferencesImpl$EditorImpl$1.$$robo$$run(SharedPreferencesImpl.java:416)
	at java.lang.invoke.LambdaForm$DMH/125881207.invokeSpecial_L_V(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/398572781.guardWithCatch(LambdaForm$MH)
	at java.lang.invoke.LambdaForm$reinvoker/1405747618.dontInline(LambdaForm$reinvoker)
	at java.lang.invoke.LambdaForm$MH/898406901.guard(LambdaForm$MH)
	at java.lang.invoke.LambdaForm$MH/1054932644.linkToCallSite(LambdaForm$MH)
	at android.app.SharedPreferencesImpl$EditorImpl$1.run(SharedPreferencesImpl.java)
	at android.app.QueuedWork.$$robo$$waitToFinish(QueuedWork.java:189)
	at java.lang.invoke.LambdaForm$DMH/1447689627.invokeStatic__V(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/1954471782.guardWithCatch(LambdaForm$MH)
	at java.lang.invoke.LambdaForm$reinvoker/777379084.dontInline(LambdaForm$reinvoker)
	at java.lang.invoke.LambdaForm$MH/1950701640.guard(LambdaForm$MH)
	at java.lang.invoke.LambdaForm$MH/243194708.linkToCallSite(LambdaForm$MH)
	at android.app.QueuedWork.waitToFinish(QueuedWork.java)
	at org.robolectric.shadows.ShadowQueuedWork.reset(ShadowQueuedWork.java:15)
	at org.robolectric.Shadows.reset(Shadows.java:1720)
	at org.robolectric.Robolectric.reset(Robolectric.java:42)
	at org.robolectric.android.internal.ParallelUniverse.resetStaticState(ParallelUniverse.java:53)
	at org.robolectric.RobolectricTestRunner.lambda$afterTest$1(RobolectricTestRunner.java:346)
	at org.robolectric.RobolectricTestRunner$$Lambda$10/767165873.run(Unknown Source)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:72)
	at org.robolectric.RobolectricTestRunner.afterTest(RobolectricTestRunner.java:345)
```

During these tests, there's an exception that's being thrown by a background thread: 
```
Exception in thread "SearchEngines-Load" java.lang.NullPointerException
	at org.robolectric.shadows.ShadowAssetManager.getAssetsDirectory(ShadowAssetManager.java:986)
	at org.robolectric.shadows.ShadowAssetManager.getAllAssetsDirectories(ShadowAssetManager.java:980)
	at org.robolectric.shadows.ShadowAssetManager.findAssetFile(ShadowAssetManager.java:335)
	at org.robolectric.shadows.ShadowAssetManager.open(ShadowAssetManager.java:316)
	at android.content.res.AssetManager.open(AssetManager.java)
	at org.mozilla.focus.search.SearchEngineParser.load(SearchEngineParser.java:35)
	at org.mozilla.focus.search.SearchEngineManager.loadFromDisk(SearchEngineManager.java:220)
	at org.mozilla.focus.search.SearchEngineManager.access$000(SearchEngineManager.java:57)
	at org.mozilla.focus.search.SearchEngineManager$1.run(SearchEngineManager.java:180)
```

I was thinking we might be deadlocked (some SessionManager methods rely on SearchEngineManager) but my log statements and breakpoints where we wait on SearchEngineManager are not getting executed.

**Comment by mcomella** [comment]
I'm going to set this aside for now: this gives us instant run and gets us up-to-date but perhaps isn't worth blocking further refactor work on, especially when I can build a workaround.

**Comment by mcomella** [comment]
Sorry to make you review this – this isn't working and I set it aside. The tests hang in the AmazonWebViewBeta/Release and I can't figure out why.

> How do you accept the license agreement on TC tasks? It looks like we need to do that for gradle 3

lol, I have no idea. I didn't know I accept a gradle agreement. :|

**Comment by mcomella** [comment]
Going to close this because I'm not actively working on it.

**Pull request closed without merging**
