### PR TITLE
Issue #2378: Set kotlin incremental false!!! !!

### PR DESCRIPTION
**Pull request by dnarcese**
Connected to #???

## Checklist

- [ ] Confirm the  **acceptance criteria is/are fully satisfied** in the issue(s) this PR will close
- [ ] Add **testing notes and/or screenshots** in PR description to help guide all potential reviewers
- [ ] Add thorough **tests** or an explanation of why it does not
- [ ] Add a **CHANGELOG entry** if applicable
- [ ] Add **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-denied`)

### CODE REVIEW

**Comment by mcomella** [comment]
The previous run on the old instance types FAILED with the timeout error.

I retriggered after bstack updated the instance types to see if we can still reproduce the failures.

**Comment by dnarcese** [comment]
> I retriggered after bstack updated the instance types to see if we can still reproduce the failures.
Still reproducible

**Comment by dnarcese** [comment]
Failing on `unpinTileFromContextMenu` test failure.

**Comment by dnarcese** [comment]
Pass 1/1

**Pull request closed without merging**
