### PR TITLE
Bug 1608153 - Do not trigger a new build on every single action that …

### PR DESCRIPTION
**Pull request by JohanLorenzo**
…occurs on a PR

## Checklist

- [ ] Confirm the **acceptance criteria** is fully satisfied in the issue(s) this PR will close
- [ ] Add thorough **tests** or an explanation of why it does not
- [ ] Add a **CHANGELOG entry** if applicable
- [ ] Add **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-notneeded`)

### CODE REVIEW

**Comment by mcomella** [comment]
@JohanLorenzo I would like to put off reviewing this until Fenix code freeze: is that okay? If not, is this PR also completed on another project, like Fenix? If it's just copied from another repository, I can rubberstamp it as "looks about right".

**Comment by mcomella** [comment]
@JohanLorenzo I'm also happy for Mitch or someone else to review this and I can rubberstamp.

**Comment by JohanLorenzo** [comment]
> @JohanLorenzo I would like to put off reviewing this until Fenix code freeze: is that okay?

No problem, I understand 🙂 This PR is not urgent, so no need to get it landed right away. For reference, I opened the same in Fenix https://github.com/mozilla-mobile/fenix/pull/8046, and almost the same in AC https://github.com/mozilla-mobile/android-components/pull/5788  

> @JohanLorenzo I'm also happy for Mitch or someone else to review this and I can rubberstamp.

For the record, Mitch is not on Releng anymore. I can loop @MihaiTabara in, though 🙂

**Comment by mcomella** [comment]
@JohanLorenzo Okay, I will wait for one of them to be reviewed. To be explicit, I'm very excited for this change as I've been concerned by the wastefulness that our current set up causes. :) Quick question: how can we re-run builds now?

**Comment by JohanLorenzo** [comment]
Closing and reopening a PR will trigger the`"reopened"` event which will make TC run a new graph 👍

**Comment by mcomella** [comment]
Thanks everyone!

**Pull request merged**
